/** Hand-maintained short names. Values must exist in `generated.ts`; sync fails otherwise. */
export const aliases: Record<string, string> = {
  bigquery: 'bigquery',
  cloudarmor: 'cloud-armor',
  cloudbuild: 'cloud-build',
  cloudrun: 'cloud-run',
  cloudsql: 'cloud-sql',
  cloudstorage: 'cloud-storage',
  firestore: 'firestore',
  gce: 'compute-engine',
  gcs: 'cloud-storage',
  gke: 'google-kubernetes-engine',
  iam: 'identity-and-access-management',
  lb: 'cloud-load-balancing',
  memorystore: 'memorystore',
  pubsub: 'pubsub',
  run: 'cloud-run',
  secretmanager: 'secret-manager',
  spanner: 'cloud-spanner',
  vpc: 'virtual-private-cloud',
}
