/** Hand-maintained short names. Values must exist in `generated.ts`; sync fails otherwise. */
export const aliases: Record<string, string> = {
  cloudflare: 'cloudflare',
  docker: 'docker',
  expo: 'expo',
  fastapi: 'fastapi',
  firebase: 'firebase',
  go: 'go',
  grafana: 'grafana',
  kafka: 'apachekafka',
  kubernetes: 'kubernetes',
  mongo: 'mongodb',
  mongodb: 'mongodb',
  mysql: 'mysql',
  nextjs: 'nextdotjs',
  nginx: 'nginx',
  node: 'nodedotjs',
  postgres: 'postgresql',
  postgresql: 'postgresql',
  prometheus: 'prometheus',
  python: 'python',
  rabbitmq: 'rabbitmq',
  react: 'react',
  redis: 'redis',
  sentry: 'sentry',
  stripe: 'stripe',
  supabase: 'supabase',
  terraform: 'terraform',
  typescript: 'typescript',
  vercel: 'vercel',
}
