/**
 * Rebuilds an icon package from the provider's official icon archive. Maintainer-only;
 * the only code that uses the network. Review `git diff` before committing.
 *
 *   pnpm icons:sync aws                      # uses the pinned URL in icon-sources.json
 *   pnpm icons:sync aws --from ./assets.zip  # or a local download
 */
import { execFileSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { readdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { basename, dirname, join, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { optimize } from 'svgo'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')

interface Source {
  url: string | null
  note: string
  include: string
  stripPrefixes: string[]
  stripSuffixes: string[]
  /** Archive path to a `[{ title, hex }]` list. Monochrome sets need it to gain brand colour. */
  colorData?: string
}

async function main() {
  const [provider, ...rest] = process.argv.slice(2)
  if (!provider) fail('Usage: pnpm icons:sync <aws|gcp> [--from <zip path or url>]')

  const sources: Record<string, Source> = JSON.parse(
    readFileSync(join(here, 'icon-sources.json'), 'utf8'),
  )
  const source = sources[provider]
  if (!source) fail(`Unknown provider '${provider}'. Known: ${Object.keys(sources).join(', ')}`)

  const fromIndex = rest.indexOf('--from')
  const from = fromIndex >= 0 ? rest[fromIndex + 1] : source.url
  if (!from) {
    fail(
      `No archive for '${provider}'.\n  ${source.note}\n` +
        `  Download it, then run: pnpm icons:sync ${provider} --from <path>\n` +
        `  and pin the URL in scripts/icon-sources.json so the next sync is one command.`,
    )
  }

  const packageDir = join(repoRoot, 'packages', `icons-${provider}`)
  if (!existsSync(packageDir)) fail(`No package at ${packageDir}`)

  const work = mkdtempSync(join(tmpdir(), `archdraw-icons-${provider}-`))
  try {
    const archive = from.startsWith('http') ? await download(from, work) : resolve(from)
    execFileSync('unzip', ['-qo', archive, '-d', join(work, 'extracted')])

    const include = new RegExp(source.include)
    const files = (await walk(join(work, 'extracted'))).filter(
      (file) => include.test(file) && !isArchiveJunk(file),
    )
    if (files.length === 0) fail(`Archive contained no files matching ${source.include}`)

    const svgDir = join(packageDir, 'svg')
    rmSync(svgDir, { recursive: true, force: true })
    mkdirSync(svgDir, { recursive: true })

    const colors = source.colorData ? readColors(join(work, 'extracted'), source.colorData) : null

    const assets = new Map<string, { viewBox: string; content: string }>()
    for (const file of files) {
      const slug = slugify(basename(file, '.svg'), source)
      if (assets.has(slug)) continue
      const optimized = optimize(readFileSync(file, 'utf8'), {
        multipass: true,
        plugins: [
          'preset-default',
          // Icons share one SVG document; unprefixed ids collide.
          { name: 'prefixIds', params: { prefix: slug } },
        ],
      }).data

      const viewBox = /viewBox="([^"]+)"/.exec(optimized)?.[1]
      let content = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(optimized)?.[1]
      if (!viewBox || !content) {
        console.warn(`  skipped ${basename(file)} — no viewBox or empty body`)
        continue
      }
      if (colors) {
        const title = /<title>([^<]*)<\/title>/.exec(content)?.[1]
        const hex = title ? colors.get(decodeEntities(title)) : undefined
        if (!hex) {
          console.warn(`  no brand colour for ${basename(file)} — left monochrome`)
        } else {
          content = content.replace(/<path /g, `<path fill="#${hex}" `)
        }
      }

      writeFileSync(join(svgDir, `${slug}.svg`), optimized)
      assets.set(slug, { viewBox, content: content.trim() })
    }

    const slugs = [...assets.keys()].sort()
    writeFileSync(
      join(packageDir, 'src', 'generated.ts'),
      `// Generated by \`pnpm icons:sync ${provider}\`. Do not edit by hand.\n` +
        `import type { IconAsset } from './types.js'\n\n` +
        `export const icons: Record<string, IconAsset> = ${JSON.stringify(
          Object.fromEntries(slugs.map((slug) => [slug, assets.get(slug)])),
          null,
          2,
        )}\n`,
    )

    const aliasesSource = readFileSync(join(packageDir, 'src', 'aliases.ts'), 'utf8')
    const dangling = [...aliasesSource.matchAll(/^\s*[\w'"-]+:\s*'([^']+)'/gm)]
      .map((match) => match[1] as string)
      .filter((slug) => !assets.has(slug))
    if (dangling.length > 0) {
      fail(
        `aliases.ts points at slugs this archive does not contain:\n  ${[...new Set(dangling)].join('\n  ')}\n` +
          `  Fix them against svg/ — a dangling alias becomes an "Unknown type" error for users.`,
      )
    }

    console.log(`${provider}: ${slugs.length} icons written to ${svgDir}`)
    console.log('Review `git diff` before committing.')
  } finally {
    rmSync(work, { recursive: true, force: true })
  }
}

/** SVGO escapes `&` and friends in titles; the colour table holds the raw text. */
function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code: string) =>
      String.fromCodePoint(Number.parseInt(code, 16)),
    )
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(Number(code)))
}

/** Title -> brand hex, keyed by the `<title>` each icon already carries. */
function readColors(root: string, relative: string): Map<string, string> {
  const [dir] = readdirSync(root)
  const path = join(root, dir ?? '', relative)
  const parsed = JSON.parse(readFileSync(path, 'utf8')) as
    | { title: string; hex: string }[]
    | { icons: { title: string; hex: string }[] }
  const list = Array.isArray(parsed) ? parsed : parsed.icons
  return new Map(list.map((icon) => [icon.title, icon.hex]))
}

/** AppleDouble twins (`._name.svg`) match the include pattern but hold xattrs, not SVG. */
function isArchiveJunk(file: string): boolean {
  return basename(file).startsWith('._') || file.includes(`${sep}__MACOSX${sep}`)
}

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const out: string[] = []
  for (const entry of entries) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(path)))
    else out.push(path)
  }
  return out
}

async function download(url: string, work: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) fail(`GET ${url} -> ${response.status} ${response.statusText}`)
  const target = join(work, 'archive.zip')
  writeFileSync(target, Buffer.from(await response.arrayBuffer()))
  return target
}

function slugify(name: string, source: Source): string {
  let out = name
  for (const prefix of source.stripPrefixes) {
    if (out.startsWith(prefix)) out = out.slice(prefix.length)
  }
  for (const suffix of source.stripSuffixes) {
    if (out.endsWith(suffix)) out = out.slice(0, -suffix.length)
  }
  // Split on separators only: brand names are camel-cased (DynamoDB, SageMaker).
  return out
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function fail(message: string): never {
  console.error(message)
  process.exit(1)
}

await main()
